### PR TITLE
Fix paypal resolving showPaymentViewController promise at the wrong time

### PR DESCRIPTION
**Pull request by TSMMark**

### CODE REVIEW

**Comment by TSMMark** [comment]
This fixes a bug where after adding a new PayPal,

simulator screen shot jan 18 2017 5 16 51 pm

The `showPaymentViewController` promise is resolved with a nonce. This is wrong because the promise should not be resolved until `Pay` is clicked:

simulator screen shot jan 18 2017 5 17 08 pm

Then, when `Pay` is clicked, you get an error because the promise is trying to be resolved again:

simulator screen shot jan 18 2017 5 19 15 pm

**Comment by TSMMark** [comment]
@kraffslol let me know if there's anything else I can do to get this merged

**Comment by kraffslol** [comment]
Looks good to me. Thanks!

**Comment by TSMMark** [comment]
I think we may have broken adding a first Paypal Account when the customer has no payment methods saved in the vault yet.

**Pull request merged**
