### PR TITLE
Customisation of text for call to action button

### PR DESCRIPTION
**Pull request by adrianchinghc**
I am currently working on saving payment method for customers and hence the built-in call to action text on the button('Pay') isn't very suitable for the use case. Hence, this PR to enable customisation of the call to action button.

### CODE REVIEW

**Comment by jeveloper** [comment]
Thanks for your work, i think you should have control over the project too

**Comment by kraffslol** [comment]
This looks great! Although the payment button seems to require the callToActionText option to be supplied, otherwise it returns "(null)" instead of the default button text. Could you perhaps make this option optional? That way it won't break for people updating from an older version.

**Comment by adrianchinghc** [comment]
@kraffslol Just made a small change to the js code so that it will use the text "Pay" if callToActionText option is not supplied.

**Comment by kraffslol** [comment]
I believe the payment button is localised by the phone language by default, so if someone uses another language than English "Pay" may look out of place. How about placing it in an if clause checking if callToActionText is set inside the ios/android code? Like it's done [here](https://github.com/adrianchinghc/react-native-braintree-xplat/blob/390aa0a7efac070d88891c428c8a3fe7bad170a1/ios/RCTBraintree/RCTBraintree.m#L74-L75).

**Comment by adrianchinghc** [comment]
@kraffslol Agree. Updated the code to make it optional in the android and ios code.

**Comment by kraffslol** [comment]
Well done! Works great. Thank you so much! 👍

**Pull request merged**
